export const UPDATE_FILTERED_CATEGORIES = 'UPDATE_FILTERED_CATEGORIES'
export const UPDATE_FILTERED_COLLABORATION_TYPES = 'UPDATE_FILTERED_COLLABORATION_TYPES'
export const TOGGLE_FILTER_FOLLOWINGS = 'TOGGLE_FILTER_FOLLOWINGS'
export const TOGGLE_FILTER_FAVORINGS = 'TOGGLE_FILTER_FAVORINGS'
export const SET_LOCATION_FILTER = 'SET_LOCATION_FILTER'
export const TOGGLE_BOUNDINBOX_FILTER = 'TOGGLE_BOUNDINBOX_FILTER'

export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_BOUNDING_BOX = 'SET_BOUNDING_BOX'
